### ISSUE TITLE
gulp --production build errors

### ISSUE THREAD

**Issue by kino90** [fevrcoding/wok#32]
Hello, 
On a clean project when I build with gulp --production i get some wrong files inside assets folder.

```
 assets/stylesheets/
  - application-1c964ac21c.min.css
  - application-1c964ac21c.min.html <---- this file is wrong!!
  - application.min.css
  - application.min.css.map
```

Also, those .html files get injected inside the compiled views

**Comment by kino90** [comment]
if this could help.. those html files are also created inside the assets folder

**Comment by liqueflies** [comment]
Hi, sould be fixed in this PR:

https://github.com/fevrcoding/wok/pull/33

if you have in a project in `views.js` move the line `.pipe(useRef())` after the `.pipe($.rename...` step. :)
