### ISSUE TITLE
Moving to Nunjucks

### ISSUE THREAD

**Issue by dwightjack** [fevrcoding/wok#4]
I was wondering if it's worth moving to [Nunjucks](https://mozilla.github.io/nunjucks/) since it's way more powerfull and ejs

**Comment by samuelecarpene** [comment]
+1 for nunjucks. Very nice and easy templating language!

**Comment by dwightjack** [comment]
Closed by 8e6cd1faf5d81c31747f13d55f9f9eea17a55c73
